name: way-share
recipe: drupal10
config:
  webroot: web
  via: nginx
  php: 8.2
proxy:
  mailhog:
    - mail.lemp.lndo.site
services:
  appserver:
    type: php:8.1
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
tooling:
  drush:
    service: appserver
    env:
      DRUSH_OPTIONS_URI: "http://way-share.lndo.site/"
